version: '3.11'
services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: python app.py
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_init
    volumes:
      - ./data:/var/lib/postgresql/data